server:
  port: 8086

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: antkatorets@gmail.com
    password: wbwm yolz bsuk mmpv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  kafka:
    consumer:
      group-id: notification-group-replay-1
      auto-offset-reset: earliest
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    listener:
      missing-topics-fatal: false
    properties:
      spring.json.trusted.packages: "*"