server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            -  id: root-redirect
               uri: http://localhost:8081
               predicates:
                - Path=/
               filters:
                  - RedirectTo=302, /products
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**

            - id: product-service
              uri: http://localhost:8081
              predicates:
               - Path=/products/**

            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/cart/**

            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/order/**

            - id: user-service
              uri: http://localhost:8085
              predicates:
                - Path=/user/**, /profile, /profile/**

