spring:
  application:
    name: admin-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    cache: false

server:
  port: 8111

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
