spring:
  application:
    name: cart-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    cache: false

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
